JSBasics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.api_proxy.urls', namespace='api_proxy')),
    path('u/', include('apps.login_reg.urls', namespace='login_reg')),
    path('admin/', admin.site.urls),
]

apps/api_proxy/urls.py
from django.urls import path
from . import views

app_name = 'api_proxy'

urlpatterns = [
    path('', views.index, name='index'),
    path('data', views.data, name='data'),
]

apps/login_reg/urls.py
from django.urls import path
from . import views

app_name = 'login_reg'

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('authenticate_ajax/<str:auth_for>', views.authenticate_ajax, name='authenticate_ajax'),
]

apps/api_proxy/models.py
from django.db import models

apps/login_reg/models.py
from django.db import models


class User(models.Model):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=256)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/api_proxy/views.py
import json, requests

from django.http import JsonResponse
from django.shortcuts import render


def index(request):
    return render(request, 'api_proxy/index.html')

def data(request):
    if request.method == 'POST':
        try:
            return JsonResponse(requests.get(request.POST['url']).text, safe=False)
        except:
            return JsonResponse({'error': 'Request failed'})

    return JsonResponse({'error': 'GET request not allowed'})

apps/login_reg/views.py
import bcrypt, json
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
from pprint import pprint

from apps.login_reg.models import User

def logout(request):
    request.session.clear()
    return redirect('api_proxy:index')


def login(request):
    if 'user_id' in request.session:
        return redirect('api_proxy:index')
        
    return render(request, 'login_reg/login.html')

def register(request):
    if 'user_id' in request.session:
        return redirect('api_proxy:index')

    return render(request, 'login_reg/register.html')

def authenticate_ajax(request, auth_for):
    if (request.method == 'POST'):
        success = False
        user = None

        if (auth_for == 'register'):
            success, user = register_user(request)

        if auth_for == 'login':
            success, user = login_user(request)

        if (success):
            start_session(request, user)
            return JsonResponse({ "url": redirect('api_proxy:index').url })

        errors = []
        for message in messages.get_messages(request):
            errors.append(str(message))

        return JsonResponse({ 'errors': errors }, status=400)

    return JsonResponse({ 'message': 'method not allowed' })



def login_user(request):
    email = request.POST['html_email']
    password = request.POST['html_password']
    is_valid = check_length(request, email, 'Email')
    is_valid = check_length(request, password, 'Password')

    if is_valid:
        try:
            user = User.objects.get(email=email)
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                return True, user
            else:
                messages.error(request, 'Invalid email or password')
        except:
            messages.error(request, 'Email not found. Please register.')

    return False, None



def register_user(request):
    username = request.POST['html_username']
    email = request.POST['html_email']
    password = request.POST['html_password']
    confirm = request.POST['html_confirm']

    is_valid = check_length(request, username, 'Full name')
    is_valid = check_length(request, email, 'Email')
    is_valid = check_length(request, password, 'Password')
    is_valid = check_length(request, confirm, 'Confirm password')

    if password != confirm:
        messages.error(request, 'Passwords do not match')
        is_valid = False

    if is_valid:
        try:
            user = User.objects.create(username=username, email=email, password=bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'))
            return True, user
        except:
            messages.error(request, 'That email address is already in use.  Please use a different email address.')

    
    return False, None


def start_session(request, user):
    request.session['user_id'] = user.id
    request.session['username'] = user.username


def check_length(request, data, name):
    if len(data) == 0:
        messages.error(request, name + ' cannot be left blank')
        return False

    return True

apps/api_proxy/templates/api_proxy/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>ChannelOne</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'api_proxy/lib/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'api_proxy/lib/font-awesome.min.css' %}">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'api_proxy/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'api_proxy/css/default.css' %}">


</head>

<body>
    <div><a href="{% url 'login_reg:login' %}">Login</a></div>
    <div><a href="{% url 'login_reg:logout' %}">Logout</a></div>
    <div><a href="{% url 'login_reg:register' %}">Register</a></div>
    {% block body %} {% endblock %}


    <script src="{% static 'api_proxy/lib/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'api_proxy/lib/popper.min.js' %}"></script>
    <script src="{% static 'api_proxy/lib/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.0/js.cookie.min.js"></script>
    <script src="{% static 'api_proxy/js/utilities.js' %}"></script>

    {% block scripts %} {% endblock %}
</body>

</html>

apps/api_proxy/templates/api_proxy/index.html
{% extends 'api_proxy/base.html' %} {% block body %}


<div class="container mt-3">
    <h1>API Proxy Stuff</h1>
    <form action="{% url 'api_proxy:data' %}" method="POST">
        <div class="form-row">
            <input type="text" class="form-control col-8" name="api-url" value="http://data.coding.kitchen/api/cities/1">
            <button class="btn btn-primary ml-2">Get</button>
            <i class="fa fa-spinner fa-spin call"></i>
            {% csrf_token %}
        </div>
    </form>

    <div class="results mt-3">
        <div class="scroller"></div>
    </div>
</div>

{% endblock %} {% block scripts %}

<script>

    $(document).ready(function () {
        
        /////////// CODING KITCHEN API
        
        let findCapitals = function (response) {
            if (Array.isArray(response)) {
                console.log("dealing with an array");
            }
        }
        
        let findProfitableCompanies = function (response) {

        }

        /////////// CODING KITCHEN API


        makeApiCall(findCapitals);
    });

</script> {% endblock %}

apps/login_reg/templates/login_reg/login.html
{% extends 'api_proxy/base.html' %} {% block body %}

<div class="card my-4 col-6 offset-3 p-5">
    <h3 class="text-center">Login</h3>
    <form method="POST" action="{% url 'login_reg:authenticate_ajax' auth_for='login' %}" id="login-form">
        <div class="form-group">
            <label for="inputEmail1">Email</label>
            <input type="email" class="form-control" id="inputEmail1" aria-describedby="emailHelp" placeholder="Enter Email" name="html_email"
                value="">
        </div>
        <div class="form-group">
            <label for="inputPassword1">Password</label>
            <input type="password" class="form-control" id="inputPassword1" placeholder="Enter Password" name="html_password" value="">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <i class="fa fa-spinner ml-3 fa-spin" id="spinner" style="display: none"></i>
    </form>
    <div class="my-3 messages">
        
    </div>
</div>


{% endblock %} {% block scripts %}
<script>


    $(document).ready(function () {
        
    $("button").click(function(event) {
        event.preventDefault()
        console.log(event)
        $(".messages").children().remove()
        $.ajax({
            beforeSend: setCsrfToken,
            type: $("form").attr("method"),
            url: $("form").attr("action"),
            data: {
                "html_email": $("input[name=html_email]").val(),
                "html_password": encryptPassword($("input[name=html_password]").val()),
            },
            success: function (response) {
                console.log(response)
                window.location = response.url
            },
            error: function (response) {
                displayErrors($(".messages"), response.responseJSON.errors)
            }
        });
    });

    });


</script> {% endblock %}

apps/login_reg/templates/login_reg/register.html
{% extends 'api_proxy/base.html' %} {% block body %}

<div class="card my-4 col-6 offset-3 p-5">
    <h3 class="text-center">Register</h3>
    <form method="POST" action="{% url 'login_reg:authenticate_ajax' auth_for='register' %}" id="register-form">
        <div class="form-group">
            <label for="inputEmail1">Email Address</label>
            <input type="email" class="form-control" id="inputEmail1" aria-describedby="emailHelp" placeholder="Enter Email Address"
                name="html_email">
        </div>
        <div class="form-group">
            <label for="inputUserName1">Full Name</label>
            <input type="text" class="form-control" id="inputUserName1" aria-describedby="usernameHelp" placeholder="Enter UserName"
                name="html_username">
        </div>
        <div class="form-group">
            <label for="inputPassword1">Password</label>
            <input type="password" class="form-control" id="inputPassword1" placeholder="Create Password" name="html_password">
        </div>
        <div class="form-group">
            <label for="inputPassword2">Confirm Password</label>
            <input type="password" class="form-control" id="inputPassword2" placeholder="Confirm Password" name="html_confirm">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <i class="fa fa-spinner ml-3 fa-spin" id="spinner" style="display: none"></i>
    </form>

    <div class="my-3 messages">
        
    </div>
</div>

{% endblock %} {% block scripts %}

<script>

    $(document).ready(function () {
       
    $("button").click(function(event) {
        event.preventDefault()
        $(".messages").children().remove()
        $.ajax({
            beforeSend: setCsrfToken,
            type: $("form").attr("method"),
            url: $("form").attr("action"),
            data: {
                "html_email": $("input[name=html_email]").val(),
                "html_username": $("input[name=html_username]").val(),
                "html_password": encryptPassword($("input[name=html_password]").val()),
                "html_confirm": encryptPassword($("input[name=html_confirm]").val()),
            },
            success: function (response) {
                console.log(response)
                window.location = response.url
            },
            error: function (response) {
                displayErrors($(".messages"), response.responseJSON.errors)
            }
        });
    });
        
    });
</script> {% endblock %}